/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fylawallet;

//harmonyj
import one.harmony.cmd.Blockchain;
import one.harmony.common.Config;
import one.harmony.cmd.Keys;
import one.harmony.transaction.Handler;
import one.harmony.transaction.ChainID;

//Simple JsonObject
import org.json.JSONObject;

//java
import java.util.Map;
import java.util.List;
import java.lang.StringBuilder;
import java.security.SecureRandom;
import java.math.BigInteger;

//sql2o
import org.sql2o.*;
import org.sql2o.Sql2o;

//fylawallet
import fylawallet.DbMethods.*;

//spark
import spark.staticfiles.*;
import static spark.Spark.*;

public class App {
    public static Sql2o sql2o = new Sql2o("jdbc:sqlite::resource:fyla.db", null, null);

    public static ERC20 contract;
    public static Handler handler;
    public static  String ethFormattedAddress;
    public static String oneAddress;
    public static String passphrase;
    public static String node;
    public static String accountName;
    public static MyGasProvider contractGasProvider = new MyGasProvider(new BigInteger("1"), new BigInteger("6751900")); 

    public static void main(String[] args) {
        System.out.println(Keys.getKeysLocation());
        node =  "https://api.s0.t.hmny.io";
        List<AccountObject> list = DbMethods.accountInfo();
        System.out.println(list);
        Config.node = "https://api.s0.t.hmny.io";
        port(4567);
        externalStaticFileLocation("src/main/resources/public");
        new Api();
    }
}
